name: finterstellar-lecture
channels:
  - damianavila82
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - rise
  - pip:
    - jupyterlab_latex
    - bs4
    - lxml
    - urllib3
    - sklearn
    - xlrd
